theme = "dracula"

[editor]
bufferline = "multiple"
cursorline = true
color-modes = true
gutters.layout = ["diff", "diagnostics", "line-numbers", "spacer", "spacer"]
gutters.line-numbers.min-width = 3

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.select]
# from https://github.com/helix-editor/helix/pull/9080#issuecomment-2008964831
J = ["select_line_below"]
K = ["select_line_above"]

"A-j" = "join_selections"
"A-J" = "join_selections_space"

X = "remove_primary_selection"
x = "keep_selections"
"A-x" = "remove_selections"

"H" = ["goto_line_start"]
"L" = ["goto_line_end"]

[keys.normal]
# collapse multiple cursors
esc = ["collapse_selection", "keep_primary_selection"]

J = ["select_line_below"]
K = ["select_line_above"]

"H" = ["select_mode", "goto_line_start", "exit_select_mode"]
"L" = ["select_mode", "goto_line_end", "exit_select_mode"]
"A-j" = "join_selections"
"A-J" = "join_selections_space"

X = "remove_primary_selection"
x = "keep_selections"
"A-x" = "remove_selections"

"*" = ["move_prev_word_start", "move_next_word_end", "search_selection"]

[keys.normal.space]
l = ":toggle lsp.display-inlay-hints"
x = ":toggle whitespace.render all none"

[keys.normal."["]
"[" = "goto_previous_buffer"

[keys.normal."]"]
"]" = "goto_next_buffer" 

[editor.lsp]
auto-signature-help = true

[editor.statusline]
left = ["mode", "spacer", "diagnostics", "workspace-diagnostics", "spinner"]
right = ["file-name", "spacer", "position-percentage", "spacer"]


