theme = "dracula"

[editor]
bufferline = "multiple"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.select]
# from https://github.com/helix-editor/helix/pull/9080#issuecomment-2008964831
J = ["select_line_below"]
K = ["select_line_above"]

"A-j" = "join_selections"
"A-J" = "join_selections_space"

X = "remove_primary_selection"
x = "keep_selections"
"A-x" = "remove_selections"

[keys.normal]
# collapse multiple cursors
esc = ["collapse_selection", "keep_primary_selection"]

J = ["select_line_below"]
K = ["select_line_above"]
"A-j" = "join_selections"
"A-J" = "join_selections_space"

X = "remove_primary_selection"
x = "keep_selections"
"A-x" = "remove_selections"

[keys.normal.space]
l = ":toggle lsp.display-inlay-hints"
c = ":buffer-close"

