theme = "dracula"

[editor]
bufferline = "multiple"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.select]
# ";" = ["keep_primary_selection", "collapse_selection"]
# Deselect last line
X = ["extend_line_up", "extend_to_line_bounds"]
# Move whole selection up and down
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.normal]
# Select lines upwards
X = ["extend_line_up", "extend_to_line_bounds"]
# Move current line up and down
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
# collapse multiple cursors
esc = ["collapse_selection", "keep_primary_selection"]
"S-tab" = "jump_backward"
H = "goto_previous_buffer"
L = "goto_next_buffer"


[keys.normal.space]
l = ":toggle lsp.display-inlay-hints"
c = ":buffer-close"

