theme = "ayu_dark"

[editor]
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.select]
# ";" = ["keep_primary_selection", "collapse_selection"]
# Deselect last line
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.normal]
# Select lines upwards
X = ["extend_line_up", "extend_to_line_bounds"]



