[language-server.ruff-lsp]
command = "ruff-lsp"


[[language]]
name = "python"
auto-format = false
rulers = [88]
formatter = { command = "black", args = ["--quiet", "-"] }
language-servers = ["ruff-lsp", "pyright"]

