[language-server.ruff-lsp]
command = "ruff-lsp"


[[language]]
name = "python"
auto-format = false
rulers = [88]
formatter = { command = "black", args = ["--quiet", "-"] }
language-servers = ["ruff-lsp", "pyright"]

[[language]]
name = "markdown"
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
soft-wrap.wrap-indicator = ""



