[language-server.ruff-lsp]
command = "ruff-lsp"


[[language]]
name = "python"
scope = "source.python"
auto-format = false
rulers = [88]
language-servers = [
  "ruff-lsp", 
  { name = "pyright", except-features = ["format"] }
]

[[language]]
name = "markdown"
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
soft-wrap.wrap-indicator = ""



