[language-server.ruff]
command = "ruff"
args = ["server"]


[[language]]
name = "python"
scope = "source.python"
auto-format = false
rulers = [88]
language-servers = [
  { name = "pyright", except-features = ["format"] },
  "ruff"
]

[[language]]
name = "markdown"
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
soft-wrap.wrap-indicator = ""



