os:
  editPreset: 'helix (hx)'

promptToReturnFromSubprocess: false

git:
  paging:
    # pager: delta --dark --paging=never -s --true-color always --color-only
    externalDiffCommand: difft --color=always --display=side-by-side
