# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[mgr.prepend_keymap]]
on = [ "?" ]
run = "help"
desc = "Open help"

# Drag and drop via dragon
[[mgr.prepend_keymap]]
on   = [ "<C-n>" ]
run = '''
	shell 'dragon -x -T "$@"' --confirm
'''
desc = "Drag-and-drop"

# https://yazi-rs.github.io/docs/tips/#copy-selected-files-to-the-system-clipboard-while-yanking
[[mgr.prepend_keymap]]
on   = [ "y" ]
run = [ "yank", '''
	shell --confirm 'echo "$@" | xclip -i -selection clipboard -t text/uri-list'
''' ]
desc = "Yank selected files (also copy to system clipboard)"

[[mgr.prepend_keymap]]
on   = [ "<C-s>" ]
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

# [[manager.prepend_keymap]]
# on   = "l"
# run  = "plugin smart-enter"
# desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = [ "<C-g>" ]
run  = "plugin lazygit"
desc = "run lazygit"
